<a href="https://colab.research.google.com/github/Benza1611/data_viz_2022/blob/main/Pandas102.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import os

In [2]:
from google.colab import drive
drive.mount('/content/drive')
path = '/content/drive/My Drive/dataviz_2021_data'

Mounted at /content/drive

In [3]:
data_file_path = os.path.join(path,'pm-20-jan-2021.csv') 
data_df = pd.read_csv(data_file_path)

In [4]:
data_df.head()

   No. announce_date  ... district_of_onset                              risk
0    1     1/12/2020  ...               NaN  คนต่างชาติเดินทางมาจากต่างประเทศ
1    2     1/17/2020  ...               NaN  คนต่างชาติเดินทางมาจากต่างประเทศ
2    3     1/22/2020  ...             เมือง  คนต่างชาติเดินทางมาจากต่างประเทศ
3    4     1/22/2020  ...               NaN  คนต่างชาติเดินทางมาจากต่างประเทศ
4    5     1/24/2020  ...               NaN  คนต่างชาติเดินทางมาจากต่างประเทศ

[5 rows x 10 columns]

In [5]:
data_df

         No.  ...                                         risk
0          1  ...             คนต่างชาติเดินทางมาจากต่างประเทศ
1          2  ...             คนต่างชาติเดินทางมาจากต่างประเทศ
2          3  ...             คนต่างชาติเดินทางมาจากต่างประเทศ
3          4  ...             คนต่างชาติเดินทางมาจากต่างประเทศ
4          5  ...             คนต่างชาติเดินทางมาจากต่างประเทศ
...      ...  ...                                          ...
12648  12649  ...                             State Quarantine
12649  12650  ...  สัมผัสใกล้ชิดกับผู้ป่วยยืนยันรายก่อนหน้านี้
12650  12651  ...  สัมผัสใกล้ชิดกับผู้ป่วยยืนยันรายก่อนหน้านี้
12651  12652  ...                                Cluster ระยอง
12652  12653  ...  สัมผัสใกล้ชิดกับผู้ป่วยยืนยันรายก่อนหน้านี้

[12653 rows x 10 columns]

ตรวจสอบค่าใน column

In [6]:
set(data_df['province_of_onset'])

{nan,
 'กระบี่',
 'กรุงเทพมหานคร',
 'กาญจนบุรี',
 'กาฬสินธุ์',
 'กำแพงเพชร',
 'ขอนแก่น',
 'คลองใหญ่',
 'จันทบุรี',
 'ฉะเชิงเทรา',
 'ชลบุรี',
 'ชัยนาท',
 'ชัยภูมิ',
 'ชากบก',
 'ชุมพร',
 'ตรัง',
 'ตราด',
 'ตาก',
 'นครนายก',
 'นครปฐม',
 'นครพนม',
 'นครราชสีมา',
 'นครศรีธรรมราช',
 'นครสวรรค์',
 'นนทบุรี',
 'นราธิวาส',
 'น่าน',
 'บางบุตร',
 'บุรีรัมย์',
 'ปทุมธานี',
 'ประจวบคีรีขันธ์',
 'ปราจีนบุรี',
 'ปัตตานี',
 'พม่า',
 'พระนครศรีอยุธยา',
 'พะเยา',
 'พังงา',
 'พัทลุง',
 'พิจิตร',
 'พิษณุโลก',
 'ภูเก็ต',
 'มหาสารคาม',
 'มาบตาพุด',
 'มุกดาหาร',
 'ยะลา',
 'ยโสธร',
 'ระนอง',
 'ระยอง',
 'ราชบุรี',
 'ร้อยเอ็ด',
 'ลพบุรี',
 'ลำปาง',
 'ลำพูน',
 'ศรีสะเกษ',
 'สกลนคร',
 'สงขลา',
 'สตูล',
 'สมุทรปราการ',
 'สมุทรสงคราม',
 'สมุทรสาคร',
 'สมุุทรสงคราม',
 'สระบุรี',
 'สระแก้ว',
 'สิงห์บุรี',
 'สุพรรณบุรี',
 'สุราษฎร์ธานี',
 'สุรินทร์',
 'สุโขทัย',
 'หนองคาย',
 'หนองบัวลำภู',
 'หน้าพระธาตุ',
 'อำนาจเจริญ',
 'อุดรธานี',
 'อุตรดิตถ์',
 'อุทัยธานี',
 'อุบลราชธานี',
 'อ่างทอง',
 'เชียงราย',
 'เชียงใหม่',
 'เพชรบุรี',
 'เพชรบูรณ์',
 'เลย',
 'แพร่',
 'แม่ฮ่องสอน'}

In [7]:
len('สมุุทรสงคราม')

12

## ต่อตาราง

*   ต่อในแนวแกน Y (เพิ่มจำนวนข้อมูล)
*   ต่อในแนวแกน X (เพิ่มรายละเอียดของข้อมูล)

## ต่อแกน Y

In [8]:
BKK = data_df[data_df['province_of_onset']=='กรุงเทพมหานคร']
BKK.head()

   No. announce_date  ... district_of_onset                              risk
0    1     1/12/2020  ...               NaN  คนต่างชาติเดินทางมาจากต่างประเทศ
1    2     1/17/2020  ...               NaN  คนต่างชาติเดินทางมาจากต่างประเทศ
3    4     1/22/2020  ...               NaN  คนต่างชาติเดินทางมาจากต่างประเทศ
4    5     1/24/2020  ...               NaN  คนต่างชาติเดินทางมาจากต่างประเทศ
5    6     1/25/2020  ...               NaN  คนต่างชาติเดินทางมาจากต่างประเทศ

[5 rows x 10 columns]

In [9]:
KKC = data_df[data_df['province_of_onset']=='ขอนแก่น']
KKC.head()

       No.  ...                                           risk
180    181  ...                                        สนามมวย
462    463  ...    สัมผัสใกล้ชิดกับผู้ป่วยยืนยันรายก่อนหน้านี้
1466  1467  ...                  คนไทยเดินทางกลับจากต่างประเทศ
1970  1971  ...  ไปสถานที่ชุมชน เช่น ตลาดนัด สถานที่ท่องเที่ยว
2637  2638  ...                  สัมผัสผู้เดินทางจากต่างประเทศ

[5 rows x 10 columns]

### ต่อตารางให้เป็นข้อมูล 2 จังหวัด

In [10]:
dataBKKKKC = pd.concat([BKK,KKC])
dataBKKKKC

         No.  ...                                         risk
0          1  ...             คนต่างชาติเดินทางมาจากต่างประเทศ
1          2  ...             คนต่างชาติเดินทางมาจากต่างประเทศ
3          4  ...             คนต่างชาติเดินทางมาจากต่างประเทศ
4          5  ...             คนต่างชาติเดินทางมาจากต่างประเทศ
5          6  ...             คนต่างชาติเดินทางมาจากต่างประเทศ
...      ...  ...                                          ...
9334    9335  ...  สัมผัสใกล้ชิดกับผู้ป่วยยืนยันรายก่อนหน้านี้
10610  10611  ...  สัมผัสใกล้ชิดกับผู้ป่วยยืนยันรายก่อนหน้านี้
11517  11518  ...                         อยู่ระหว่างการสอบสวน
11697  11698  ...  สัมผัสใกล้ชิดกับผู้ป่วยยืนยันรายก่อนหน้านี้
11698  11699  ...  สัมผัสใกล้ชิดกับผู้ป่วยยืนยันรายก่อนหน้านี้

[2803 rows x 10 columns]

In [11]:
dataBKKKKC = pd.concat([BKK,KKC,BKK])

In [12]:
dataBKKKKC

         No.  ...                                           risk
0          1  ...               คนต่างชาติเดินทางมาจากต่างประเทศ
1          2  ...               คนต่างชาติเดินทางมาจากต่างประเทศ
3          4  ...               คนต่างชาติเดินทางมาจากต่างประเทศ
4          5  ...               คนต่างชาติเดินทางมาจากต่างประเทศ
5          6  ...               คนต่างชาติเดินทางมาจากต่างประเทศ
...      ...  ...                                            ...
12616  12617  ...    สัมผัสใกล้ชิดกับผู้ป่วยยืนยันรายก่อนหน้านี้
12617  12618  ...   ผู้ที่เดินทางมาจากต่างประเทศ และเข้า ASQ/ALQ
12618  12619  ...   ผู้ที่เดินทางมาจากต่างประเทศ และเข้า ASQ/ALQ
12619  12620  ...    สัมผัสใกล้ชิดกับผู้ป่วยยืนยันรายก่อนหน้านี้
12647  12648  ...  ไปสถานที่ชุมชน เช่น ตลาดนัด สถานที่ท่องเที่ยว

[5592 rows x 10 columns]

### ถ้าเอาตารางไม่เหมือนกันมา concat กัน

In [13]:
BKK2 = data_df[data_df['province_of_onset']=='กรุงเทพมหานคร'][['sex','age','nationality']]
BKK2.head()

    sex   age nationality
0  หญิง  61.0       China
1  หญิง  74.0       China
3   ชาย  68.0       China
4  หญิง  66.0       China
5  หญิง  33.0       China

In [14]:
KKC2 = data_df[data_df['province_of_onset']=='ขอนแก่น'][['age','nationality','sex']]
KKC2.head()

       age nationality   sex
180   33.0    Thailand   ชาย
462   36.0    Thailand  หญิง
1466  19.0    Thailand   ชาย
1970  70.0    Thailand  หญิง
2637  63.0    Thailand  หญิง

In [15]:
pd.concat([BKK2,KKC2])

        sex   age nationality
0      หญิง  61.0       China
1      หญิง  74.0       China
3       ชาย  68.0       China
4      หญิง  66.0       China
5      หญิง  33.0       China
...     ...   ...         ...
9334    ชาย  20.0    Thailand
10610   ชาย  17.0    Thailand
11517   ชาย  12.0    Thailand
11697  หญิง  17.0    Thailand
11698  หญิง  37.0    Thailand

[2803 rows x 3 columns]

In [16]:
KKC3 = data_df[data_df['province_of_onset']=='ขอนแก่น'][['age','nationality','risk']]
KKC3.head()

       age nationality                                           risk
180   33.0    Thailand                                        สนามมวย
462   36.0    Thailand    สัมผัสใกล้ชิดกับผู้ป่วยยืนยันรายก่อนหน้านี้
1466  19.0    Thailand                  คนไทยเดินทางกลับจากต่างประเทศ
1970  70.0    Thailand  ไปสถานที่ชุมชน เช่น ตลาดนัด สถานที่ท่องเที่ยว
2637  63.0    Thailand                  สัมผัสผู้เดินทางจากต่างประเทศ

In [17]:
pd.concat([BKK2,KKC3])

        sex   age nationality                                         risk
0      หญิง  61.0       China                                          NaN
1      หญิง  74.0       China                                          NaN
3       ชาย  68.0       China                                          NaN
4      หญิง  66.0       China                                          NaN
5      หญิง  33.0       China                                          NaN
...     ...   ...         ...                                          ...
9334    NaN  20.0    Thailand  สัมผัสใกล้ชิดกับผู้ป่วยยืนยันรายก่อนหน้านี้
10610   NaN  17.0    Thailand  สัมผัสใกล้ชิดกับผู้ป่วยยืนยันรายก่อนหน้านี้
11517   NaN  12.0    Thailand                         อยู่ระหว่างการสอบสวน
11697   NaN  17.0    Thailand  สัมผัสใกล้ชิดกับผู้ป่วยยืนยันรายก่อนหน้านี้
11698   NaN  37.0    Thailand  สัมผัสใกล้ชิดกับผู้ป่วยยืนยันรายก่อนหน้านี้

[2803 rows x 4 columns]

In [18]:
KKC4 = data_df[data_df['province_of_onset']=='ขอนแก่น'][['age','nationality']]
KKC4.head()

       age nationality
180   33.0    Thailand
462   36.0    Thailand
1466  19.0    Thailand
1970  70.0    Thailand
2637  63.0    Thailand

In [19]:
pd.concat([BKK2,KKC4])

        sex   age nationality
0      หญิง  61.0       China
1      หญิง  74.0       China
3       ชาย  68.0       China
4      หญิง  66.0       China
5      หญิง  33.0       China
...     ...   ...         ...
9334    NaN  20.0    Thailand
10610   NaN  17.0    Thailand
11517   NaN  12.0    Thailand
11697   NaN  17.0    Thailand
11698   NaN  37.0    Thailand

[2803 rows x 3 columns]

## ต่อแกน X

In [20]:
personal_data = data_df[['No.','sex','age','nationality']]
personal_data.head()

   No.   sex   age nationality
0    1  หญิง  61.0       China
1    2  หญิง  74.0       China
2    3  หญิง  73.0    Thailand
3    4   ชาย  68.0       China
4    5  หญิง  66.0       China

In [21]:
covid_data = data_df[['No.','announce_date','province_of_isolation','province_of_onset','risk']].sample(frac=1)
covid_data.head()

         No.  ...                                           risk
6668    6669  ...                              Cluster สมุทรสาคร
9852    9853  ...               คนต่างชาติเดินทางมาจากต่างประเทศ
11345  11346  ...  ไปสถานที่ชุมชน เช่น ตลาดนัด สถานที่ท่องเที่ยว
8519    8520  ...    สัมผัสใกล้ชิดกับผู้ป่วยยืนยันรายก่อนหน้านี้
1827    1828  ...    สัมผัสใกล้ชิดกับผู้ป่วยยืนยันรายก่อนหน้านี้

[5 rows x 5 columns]

### เอาตารางสองอันมาต่อกัน

In [22]:
personalcovid_data = personal_data.merge(covid_data)
personalcovid_data.head()

   No.   sex  ...  province_of_onset                              risk
0    1  หญิง  ...      กรุงเทพมหานคร  คนต่างชาติเดินทางมาจากต่างประเทศ
1    2  หญิง  ...      กรุงเทพมหานคร  คนต่างชาติเดินทางมาจากต่างประเทศ
2    3  หญิง  ...             นครปฐม  คนต่างชาติเดินทางมาจากต่างประเทศ
3    4   ชาย  ...      กรุงเทพมหานคร  คนต่างชาติเดินทางมาจากต่างประเทศ
4    5  หญิง  ...      กรุงเทพมหานคร  คนต่างชาติเดินทางมาจากต่างประเทศ

[5 rows x 8 columns]

In [23]:
personalcovid_data = covid_data.merge(personal_data)
personalcovid_data.head()

     No. announce_date province_of_isolation  ...   sex   age nationality
0   6669    12/30/2020             สมุทรสาคร  ...  หญิง  37.0    Thailand
1   9853      1/9/2021                   ตาก  ...  หญิง  21.0       Burma
2  11346     1/15/2021              จันทบุรี  ...  หญิง  46.0    Thailand
3   8520      1/5/2021         กรุงเทพมหานคร  ...  หญิง  31.0    Thailand
4   1828      4/2/2020         กรุงเทพมหานคร  ...  หญิง  24.0    Thailand

[5 rows x 8 columns]

# Save Table

In [24]:
personalcovid_data.to_csv(os.path.join(path,'my_processed_data.csv'))

In [25]:
personalcovid_data.to_csv('my_processed_data.csv')

# Groupby

https://www.kaggle.com/crawford/python-groupby-tutorial#

In [26]:
data_df.groupby('nationality').count()

                No.  announce_date  ...  district_of_onset  risk
nationality                         ...
Afghanistan       1              1  ...                  1     1
Albania           3              3  ...                  2     3
American          1              1  ...                  1     1
American          1              1  ...                  1     1
American Samoa    1              1  ...                  1     1
...             ...            ...  ...                ...   ...
deutsch           1              1  ...                  1     1
thailand          2              2  ...                  2     2
ต่างด้าว         21             21  ...                 21    21
ไทยใหญ่           1              1  ...                  1     1
ไทใหญ่            1              1  ...                  1     1

[100 rows x 9 columns]

In [27]:
data_df.groupby('nationality').mean()

                         No.        age
nationality
Afghanistan      4346.000000  31.000000
Albania          2377.333333  40.666667
American         3862.000000  39.000000
American         3905.000000  46.000000
American Samoa  11687.000000  21.000000
...                      ...        ...
deutsch          3898.000000  55.000000
thailand         6823.000000  53.500000
ต่างด้าว         2944.952381  20.000000
ไทยใหญ่         10379.000000  30.000000
ไทใหญ่           5983.000000  33.000000

[100 rows x 2 columns]

In [28]:
data_df.groupby('nationality')['age'].min()

nationality
Afghanistan       31.0
Albania           33.0
American          39.0
American          46.0
American Samoa    21.0
                  ...
deutsch           55.0
thailand          50.0
ต่างด้าว          13.0
ไทยใหญ่           30.0
ไทใหญ่            33.0
Name: age, Length: 100, dtype: float64

In [29]:
data_df.groupby('nationality').min(' ')

                  No.   age
nationality
Afghanistan      4346  31.0
Albania          1480  33.0
American         3862  39.0
American         3905  46.0
American Samoa  11687  21.0
...               ...   ...
deutsch          3898  55.0
thailand         6822  50.0
ต่างด้าว         2227  13.0
ไทยใหญ่         10379  30.0
ไทใหญ่           5983  33.0

[100 rows x 2 columns]

# Create Pandas table

![pandas-dataframe-shadow.jpg]()

## Dictionary (row oriented)

In [33]:
import pandas as pd

In [31]:
data_list = [ {'account':'Jones LLC','Jan':150,'Feb':200,'Mar':140},
             {'account':'Alpha Co','Jan':200,'Feb':210,'Mar':215},
             {'account':'Blue Inc','Jan':50,'Feb':90,'Mar':95},
            ]

In [32]:
data_list

[{'Feb': 200, 'Jan': 150, 'Mar': 140, 'account': 'Jones LLC'},
 {'Feb': 210, 'Jan': 200, 'Mar': 215, 'account': 'Alpha Co'},
 {'Feb': 90, 'Jan': 50, 'Mar': 95, 'account': 'Blue Inc'}]

In [35]:
df1 = pd.DataFrame(data_list)
df1

     account  Jan  Feb  Mar
0  Jones LLC  150  200  140
1   Alpha Co  200  210  215
2   Blue Inc   50   90   95

## List(row oriented)

In [53]:
data = [['Jones LLC',150,200,140],
        ['Alpha Co',200,210,215],
        ['Blue Inc',50,90,95]]
header = ['account','Jan','Feb','Mar']

In [54]:
df2 = pd.DataFrame.from_records(data,columns=header)
df2

     account  Jan  Feb  Mar
0  Jones LLC  150  200  140
1   Alpha Co  200  210  215
2   Blue Inc   50   90   95

## Dictionary (column oriented)

In [49]:
data_dict = {'account': ['Jones LLC','Alpha Co','Blue Inc'],
             'Jan': [150,200,50],
             'Feb': [200,210,90],
             'Mar': [140,215,95]
}

In [50]:
df3 = pd.DataFrame.from_dict(data_dict)
df3

     account  Jan  Feb  Mar
0  Jones LLC  150  200  140
1   Alpha Co  200  210  215
2   Blue Inc   50   90   95

## List (column oriented)

In [44]:
data_item = [['account', ['Jones LLC','Alpha Co','Blue Inc']],
             ['Jan', [150,200,50]],
             ['Feb', [200,210,90]],
             ['Mar', [140,215,95]]
            ]

In [46]:
# Bug
#df4 = pd.DataFrame.from_items(data_item)
#df4

## Quiz กลุ่ม ครั้งที่ 3

ออกแบบและสร้างตาราง pandas dataframe ที่ สามารถนำมาดึงข้อมูลด้วย pandas ได้

![image.png]()

In [60]:
region_quiz = [['อำนาจเจริญ, บึงกาฬ, บุรีรัมย์, ชัยภูมิ, กาฬสินธุ์, ขอนแก่น, เลย, มหาสารคาม, มุกดาหาร, นครพนม, นครราชสีมา, หนองบัวลำภู, หนองคาย, ร้อยเอ็ด, สกลนคร, ศรีสะเกษ, สุรินทร์, อุบลราชธานี, อุดรธานี, ยโสธร','ตะวันออกเฉียงเหนือ','ตะวันออกเฉียงเหนือ','ตะวันออกเฉียงเหนือ','ตะวันออกเฉียงเหนือ'],
            ['เชียงใหม่, เชียงราย, ลำปาง, ลำพูน, แม่ฮ่องสอน, น่าน, พะเยา, แพร่, อุตรดิตถ์','เหนือ','เหนือ','เหนือ','เหนือ'],
            ['ตาก','ตะวันตก','เหนือ','เหนือ','เหนือ' ],
            ['สุโขทัย, พิษณุโลก, พิจิตร, กำแพงเพชร, เพชรบูรณ์','กลาง','เหนือ','เหนือ','เหนือ'],
            ['นครสวรรค์, อุทัยธานี','กลาง','เหนือ','กลาง','เหนือ'],
            ['อ่างทอง, ชัยนาท, พระนครศรีอยุธยา, กรุงเทพมหานคร, ลพบุรี, นครปฐม, นนทบุรี, ปทุมธานี, สมุทรปราการ, สมุทรสาคร, สมุทรสงคราม, สระบุรี, สิงห์บุรี, สุพรรณบุรี','กลาง','กลาง','กลาง','กลาง'],
            ['นครนายก','กลาง','กลาง','ตะวันออก','กลาง'],
            ['ฉะเชิงเทรา, จันทบุรี, ชลบุรี, ปราจีนบุรี, ระยอง, สระแก้ว, ตราด','ตะวันออก','กลาง','ตะวันออก','ตะวันออก'],
            ['กาญจนบุรี, ราชบุรี','ตะวันตก','กลาง','กลาง','กลาง'],
            ['เพชรบุรี, ประจวบคีรีขันธ์','ตะวันตก','กลาง','ใต้ฝั่งตะวันออก/ใต้ฝั่งอ่าวไทย','กลาง'],
            ['ชุมพร, นครศรีธรรมราช, นราธิวาส, ปัตตานี, พัทลุง, สงขลา, สุราษฎร์ธานี, ยะลา','ใต้','ใต้','ใต้ฝั่งตะวันออก/ใต้ฝงอาวไทย','ใต'],
            ['กระบี่, พังงา, ภูเก็ต, ระนอง, สตูล, ตรัง','ใต','ใต','ใตฝงตะวนตก/ใตฝงอนดามน','ใต']]
header = ['จังหวัด','6 ภูมิภาค (ภูมิศาสตร)','4 ภูมิภาค (การเมือง)','6 ภูมิภาค (อุตุนิยมวิทยา)','5 ภูมิภาค (การท่องเที่ยว)']

In [61]:
quiz3 = pd.DataFrame.from_records(region_quiz,columns=header) 
quiz3

                                              จังหวัด  ... 5 ภูมิภาค (การท่องเที่ยว)
0   อำนาจเจริญ, บึงกาฬ, บุรีรัมย์, ชัยภูมิ, กาฬสิน...  ...        ตะวันออกเฉียงเหนือ
1   เชียงใหม่, เชียงราย, ลำปาง, ลำพูน, แม่ฮ่องสอน,...  ...                     เหนือ
2                                                 ตาก  ...                     เหนือ
3     สุโขทัย, พิษณุโลก, พิจิตร, กำแพงเพชร, เพชรบูรณ์  ...                     เหนือ
4                                นครสวรรค์, อุทัยธานี  ...                     เหนือ
5   อ่างทอง, ชัยนาท, พระนครศรีอยุธยา, กรุงเทพมหานค...  ...                      กลาง
6                                             นครนายก  ...                      กลาง
7   ฉะเชิงเทรา, จันทบุรี, ชลบุรี, ปราจีนบุรี, ระยอ...  ...                  ตะวันออก
8                                  กาญจนบุรี, ราชบุรี  ...                      กลาง
9                           เพชรบุรี, ประจวบคีรีขันธ์  ...                      กลาง
10  ชุมพร, นครศรีธรรมราช, นราธิวาส, ปัตตานี, พัทลุ...  ...                        ใต
11           กระบี่, พังงา, ภูเก็ต, ระนอง, สตูล, ตรัง  ...                        ใต

[12 rows x 5 columns]

In [ ]:
data_thai = [['6 ภูมิภาค (ภูมิศาสตร์)',150,200,140],
        ['Alpha Co',200,210,215],
        ['Blue Inc',50,90,95]]
header = ['แบ่งตาม','ตะวันออกเฉียงเหนือ','เหนือ','ตะวันตก','กลาง','ตะวันออก','ตะวันตก','ใต้','ใต้ฝั่งตะวันออก/ใต้ฝั่งอ่าวไทย','ใต้ฝั่งตะวันตก/ใต้ฝั่งอันดามัน']

In [ ]:
data_dict = {'จังหวัด': ['6 ภูมิภาค (ภูมิศาสตร์)','4 ภูมิภาค (การเมือง)','6 ภูมิภาค (อุตุนิยมวิทยา)','5 ภูมิภาค (การท่องเที่ยว)'],
             'อำนาจเจริญ': [150,200,50],
             'เหนือ': [200,210,90],
             'ตะวันตก': [140,215,95],
             'ตะวันตก': [140,215,95],
             'ตะวันตก': [140,215,95],
             'ตะวันตก': [140,215,95],

}

In [73]:
data_t = {'จังหวัด': ['อำนาจเจริญ', 'บึงกาฬ', 'บุรีรัมย์', 'ชัยภูมิ', 'กาฬสินธุ์', 'ขอนแก่น', 'เลย', 'มหาสารคาม', 'มุกดาหาร', 'นครพนม', 'นครราชสีมา', 'หนองบัวลำภู', 'หนองคาย', 'ร้อยเอ็ด', 'สกลนคร', 'ศรีสะเกษ', 'สุรินทร์', 'อุบลราชธานี', 'อุดรธานี', 'ยโสธร','เชียงใหม่', 'เชียงราย', 'ลำปาง', 'ลำพูน', 'แม่ฮ่องสอน', 'น่าน', 'พะเยา', 'แพร่', 'อุตรดิตถ์','ตาก','สุโขทัย', 'พิษณุโลก', 'พิจิตร', 'กำแพงเพชร', 'เพชรบูรณ์','นครสวรรค์', 'อุทัยธานี','อ่างทอง', 'ชัยนาท', 'พระนครศรีอยุธยา', 'กรุงเทพมหานคร', 'ลพบุรี', 'นครปฐม', 'นนทบุรี', 'ปทุมธานี', 'สมุทรปราการ','สมุทรสาคร', 'สมุทรสงคราม','สระบุรี', 'สิงห์บุรี', 'สุพรรณบุรี'],
            '6 ภูมิภาค (ภูมิศาสตร์)': ['ตะวันออกเฉียงเหนือ','ตะวันออกเฉียงเหนือ','ตะวันออกเฉียงเหนือ','ตะวันออกเฉียงเหนือ','ตะวันออกเฉียงเหนือ','ตะวันออกเฉียงเหนือ','ตะวันออกเฉียงเหนือ','ตะวันออกเฉียงเหนือ','ตะวันออกเฉียงเหนือ','ตะวันออกเฉียงเหนือ','ตะวันออกเฉียงเหนือ','ตะวันออกเฉียงเหนือ','ตะวันออกเฉียงเหนือ','ตะวันออกเฉียงเหนือ','ตะวันออกเฉียงเหนือ','ตะวันออกเฉียงเหนือ','ตะวันออกเฉียงเหนือ','ตะวันออกเฉียงเหนือ','ตะวันออกเฉียงเหนือ','ตะวันออกเฉียงเหนือ','เหนือ','เหนือ','เหนือ','เหนือ','เหนือ','เหนือ','เหนือ','เหนือ','เหนือ','ตะวันตก','กลาง','กลาง','กลาง','กลาง','กลาง','กลาง','กลาง','กลาง','กลาง','กลาง','กลาง','กลาง','กลาง','กลาง','กลาง','กลาง','กลาง','กลาง','กลาง','กลาง','กลาง'],
            '4 ภูมิภาค (การเมือง)': ['ตะวันออกเฉียงเหนือ','ตะวันออกเฉียงเหนือ','ตะวันออกเฉียงเหนือ','ตะวันออกเฉียงเหนือ','ตะวันออกเฉียงเหนือ','ตะวันออกเฉียงเหนือ','ตะวันออกเฉียงเหนือ','ตะวันออกเฉียงเหนือ','ตะวันออกเฉียงเหนือ','ตะวันออกเฉียงเหนือ','ตะวันออกเฉียงเหนือ','ตะวันออกเฉียงเหนือ','ตะวันออกเฉียงเหนือ','ตะวันออกเฉียงเหนือ','ตะวันออกเฉียงเหนือ','ตะวันออกเฉียงเหนือ','ตะวันออกเฉียงเหนือ','ตะวันออกเฉียงเหนือ','ตะวันออกเฉียงเหนือ','ตะวันออกเฉียงเหนือ','เหนือ','เหนือ','เหนือ','เหนือ','เหนือ','เหนือ','เหนือ','เหนือ','เหนือ','เหนือ','เหนือ','เหนือ','เหนือ','เหนือ','เหนือ','เหนือ','เหนือ','กลาง','กลาง','กลาง','กลาง','กลาง','กลาง','กลาง','กลาง','กลาง','กลาง','กลาง','กลาง','กลาง','กลาง'],
            '6 ภูมิภาค (อุตุนิยมวิทยา)': ['ตะวันออกเฉียงเหนือ','ตะวันออกเฉียงเหนือ','ตะวันออกเฉียงเหนือ','ตะวันออกเฉียงเหนือ','ตะวันออกเฉียงเหนือ','ตะวันออกเฉียงเหนือ','ตะวันออกเฉียงเหนือ','ตะวันออกเฉียงเหนือ','ตะวันออกเฉียงเหนือ','ตะวันออกเฉียงเหนือ','ตะวันออกเฉียงเหนือ','ตะวันออกเฉียงเหนือ','ตะวันออกเฉียงเหนือ','ตะวันออกเฉียงเหนือ','ตะวันออกเฉียงเหนือ','ตะวันออกเฉียงเหนือ','ตะวันออกเฉียงเหนือ','ตะวันออกเฉียงเหนือ','ตะวันออกเฉียงเหนือ','ตะวันออกเฉียงเหนือ','เหนือ','เหนือ','เหนือ','เหนือ','เหนือ','เหนือ','เหนือ','เหนือ','เหนือ','เหนือ','เหนือ','เหนือ','เหนือ','เหนือ','เหนือ','กลาง','กลาง','กลาง','กลาง','กลาง','กลาง','กลาง','กลาง','กลาง','กลาง','กลาง','กลาง','กลาง','กลาง','กลาง','กลาง'],
            '5 ภูมิภาค (การท่องเที่ยว)': ['ตะวันออกเฉียงเหนือ','ตะวันออกเฉียงเหนือ','ตะวันออกเฉียงเหนือ','ตะวันออกเฉียงเหนือ','ตะวันออกเฉียงเหนือ','ตะวันออกเฉียงเหนือ','ตะวันออกเฉียงเหนือ','ตะวันออกเฉียงเหนือ','ตะวันออกเฉียงเหนือ','ตะวันออกเฉียงเหนือ','ตะวันออกเฉียงเหนือ','ตะวันออกเฉียงเหนือ','ตะวันออกเฉียงเหนือ','ตะวันออกเฉียงเหนือ','ตะวันออกเฉียงเหนือ','ตะวันออกเฉียงเหนือ','ตะวันออกเฉียงเหนือ','ตะวันออกเฉียงเหนือ','ตะวันออกเฉียงเหนือ','ตะวันออกเฉียงเหนือ','เหนือ','เหนือ','เหนือ','เหนือ','เหนือ','เหนือ','เหนือ','เหนือ','เหนือ','เหนือ','เหนือ','เหนือ','เหนือ','เหนือ','เหนือ','เหนือ','เหนือ','กลาง','กลาง','กลาง','กลาง','กลาง','กลาง','กลาง','กลาง','กลาง','กลาง','กลาง','กลาง','กลาง','กลาง']
}

In [74]:
df_t = pd.DataFrame.from_dict(data_t)
df_t

            จังหวัด  ... 5 ภูมิภาค (การท่องเที่ยว)
0        อำนาจเจริญ  ...        ตะวันออกเฉียงเหนือ
1            บึงกาฬ  ...        ตะวันออกเฉียงเหนือ
2         บุรีรัมย์  ...        ตะวันออกเฉียงเหนือ
3           ชัยภูมิ  ...        ตะวันออกเฉียงเหนือ
4         กาฬสินธุ์  ...        ตะวันออกเฉียงเหนือ
5           ขอนแก่น  ...        ตะวันออกเฉียงเหนือ
6               เลย  ...        ตะวันออกเฉียงเหนือ
7         มหาสารคาม  ...        ตะวันออกเฉียงเหนือ
8          มุกดาหาร  ...        ตะวันออกเฉียงเหนือ
9            นครพนม  ...        ตะวันออกเฉียงเหนือ
10       นครราชสีมา  ...        ตะวันออกเฉียงเหนือ
11      หนองบัวลำภู  ...        ตะวันออกเฉียงเหนือ
12          หนองคาย  ...        ตะวันออกเฉียงเหนือ
13         ร้อยเอ็ด  ...        ตะวันออกเฉียงเหนือ
14           สกลนคร  ...        ตะวันออกเฉียงเหนือ
15         ศรีสะเกษ  ...        ตะวันออกเฉียงเหนือ
16         สุรินทร์  ...        ตะวันออกเฉียงเหนือ
17      อุบลราชธานี  ...        ตะวันออกเฉียงเหนือ
18         อุดรธานี  ...        ตะวันออกเฉียงเหนือ
19            ยโสธร  ...        ตะวันออกเฉียงเหนือ
20        เชียงใหม่  ...                     เหนือ
21         เชียงราย  ...                     เหนือ
22            ลำปาง  ...                     เหนือ
23            ลำพูน  ...                     เหนือ
24       แม่ฮ่องสอน  ...                     เหนือ
25             น่าน  ...                     เหนือ
26            พะเยา  ...                     เหนือ
27             แพร่  ...                     เหนือ
28        อุตรดิตถ์  ...                     เหนือ
29              ตาก  ...                     เหนือ
30          สุโขทัย  ...                     เหนือ
31         พิษณุโลก  ...                     เหนือ
32           พิจิตร  ...                     เหนือ
33        กำแพงเพชร  ...                     เหนือ
34        เพชรบูรณ์  ...                     เหนือ
35        นครสวรรค์  ...                     เหนือ
36        อุทัยธานี  ...                     เหนือ
37          อ่างทอง  ...                      กลาง
38           ชัยนาท  ...                      กลาง
39  พระนครศรีอยุธยา  ...                      กลาง
40    กรุงเทพมหานคร  ...                      กลาง
41           ลพบุรี  ...                      กลาง
42           นครปฐม  ...                      กลาง
43          นนทบุรี  ...                      กลาง
44         ปทุมธานี  ...                      กลาง
45      สมุทรปราการ  ...                      กลาง
46        สมุทรสาคร  ...                      กลาง
47      สมุทรสงคราม  ...                      กลาง
48          สระบุรี  ...                      กลาง
49        สิงห์บุรี  ...                      กลาง
50       สุพรรณบุรี  ...                      กลาง

[51 rows x 5 columns]